added new test for gsl to configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2297,7 +2297,7 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 # check for MacOS and append the architecture flag
 if test `uname` == "Darwin"
 then
-  CFLAGS="$CFLAGS -arch x86_64"
+  CXXFLAGS="$CXXFLAGS -arch x86_64"
 fi
 
 # check to see if the user gave us a location for the BAMTools headers
@@ -2720,32 +2720,21 @@ else
   echo "checking for linking against gsl matrix... yes"
 fi
 
-if test "$ac_cv_lib_m_cos" != yes
+if test "$ac_cv_lib_m_cos" != yes -a \
+        "$ac_cv_lib_gsl_gsl_blas_dgemm" != yes -a \
+        "$ac_cv_lib_gslcblas_cblas_dgemm" != yes -a \
+        "$ac_cv_lib_gsl_matrix" ! = yes
 then
-  { { echo "$as_me:$LINENO: error: could not find GSL -- Piranha requires GSL and cannot be built without it" >&5
-echo "$as_me: error: could not find GSL -- Piranha requires GSL and cannot be built without it" >&2;}
+  { { echo "$as_me:$LINENO: error: could not find or link to GSL -- Piranha requires GSL and \
+                cannot be built without it. GSL can be downloaded from \
+                http://www.gnu.org/software/gsl/ -- please ensure GSL is
+                correctly installed on your system." >&5
+echo "$as_me: error: could not find or link to GSL -- Piranha requires GSL and \
+                cannot be built without it. GSL can be downloaded from \
+                http://www.gnu.org/software/gsl/ -- please ensure GSL is
+                correctly installed on your system." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test "$ac_cv_lib_gsl_gsl_blas_dgemm" != yes
-then
-  { { echo "$as_me:$LINENO: error: could not find GSL -- Piranha requires GSL and cannot be built without it" >&5
-echo "$as_me: error: could not find GSL -- Piranha requires GSL and cannot be built without it" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test "$ac_cv_lib_gslcblas_cblas_dgemm" != yes
-then
-  { { echo "$as_me:$LINENO: error: could not find GSL -- Piranha requires GSL and cannot be built without it" >&5
-echo "$as_me: error: could not find GSL -- Piranha requires GSL and cannot be built without it" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test "$ac_cv_lib_gsl_matrix" != yes
-then
-  { { echo "$as_me:$LINENO: error: could not find GSL -- Piranha requires GSL and cannot be built without it" >&5
-echo "$as_me: error: could not find GSL -- Piranha requires GSL and cannot be built without it" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
 
 if test "$ac_cv_lib_bamtools_BamAlignment" != yes
 then
