fixing problem in configure with library dependencies and linking order on Ubuntu

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2313,8 +2313,66 @@ else
 echo "$as_me: no BAMTools library directory specified" >&6;}
 fi
 
-# check for gsl
+# check for BAMTools
+SAVED_LDFLAGS=$LDFLAGS
+SAVED_CXXFLAGS=$CXXFLAGS
+CXXFLAGS="$CXXFLAGS -Wl,--no-as-needed"
+if test "$BAM_LIBRARIES_DIR" != ""
+then
+  LDFLAGS="$LDFLAGS -L$BAM_LIBRARIES_DIR -lbamtools"
+fi
+if test "$BAM_HEADERS_DIR" != ""
+then
+  CXXFLAGS="$CXXFLAGS -I$BAM_HEADERS_DIR"
+fi
 
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "api/BamAlignment.h"
+int
+main ()
+{
+BamTools::BamAlignment dummy
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_bamtools_BamAlignment=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LDFLAGS=$SAVED_LDFLAGS
+CXXFLAGS=$SAVED_CXXFLAGS
+
+# check for gsl
 
 { echo "$as_me:$LINENO: checking for cos in -lm" >&5
 echo $ECHO_N "checking for cos in -lm... $ECHO_C" >&6; }
@@ -2528,63 +2586,6 @@ _ACEOF
 
 fi
 
-
-# check for BAMTools
-SAVED_LDFLAGS=$LDFLAGS
-SAVED_CXXFLAGS=$CXXFLAGS
-if test "$BAM_LIBRARIES_DIR" != ""
-then
-  LDFLAGS="$LDFLAGS -L$BAM_LIBRARIES_DIR -lbamtools"
-fi
-if test "$BAM_HEADERS_DIR" != ""
-then
-  CXXFLAGS="$CXXFLAGS -I$BAM_HEADERS_DIR"
-fi
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include "api/BamAlignment.h"
-int
-main ()
-{
-BamTools::BamAlignment dummy
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_bamtools_BamAlignment=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LDFLAGS=$SAVED_LDFLAGS
-CXXFLAGS=$SAVED_CXXFLAGS
 
 if test "$ac_cv_lib_gsl_gsl_blas_dgemm" == no
 then
