added new test for gsl to configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2720,19 +2720,32 @@ else
   echo "checking for linking against gsl matrix... yes"
 fi
 
-if test "$ac_cv_lib_m_cos" != yes -a \
-        "$ac_cv_lib_gsl_gsl_blas_dgemm" != yes -a \
-        "$ac_cv_lib_gslcblas_cblas_dgemm" != yes -a \
-        "$ac_cv_lib_gsl_matrix" ! = yes
+GSLERROR="could not find or link to GSL -- Piranha requires GSL and \
+         cannot be built without it. GSL can be downloaded from \
+         http://www.gnu.org/software/gsl/ -- please ensure GSL is \
+         correctly installed on your system."
+if test "$ac_cv_lib_m_cos" != yes
 then
-  { { echo "$as_me:$LINENO: error: could not find or link to GSL -- Piranha requires GSL and \
-                cannot be built without it. GSL can be downloaded from \
-                http://www.gnu.org/software/gsl/ -- please ensure GSL is
-                correctly installed on your system." >&5
-echo "$as_me: error: could not find or link to GSL -- Piranha requires GSL and \
-                cannot be built without it. GSL can be downloaded from \
-                http://www.gnu.org/software/gsl/ -- please ensure GSL is
-                correctly installed on your system." >&2;}
+  { { echo "$as_me:$LINENO: error: $GSLERROR" >&5
+echo "$as_me: error: $GSLERROR" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "$ac_cv_lib_gsl_gsl_blas_dgemm" != yes
+then
+  { { echo "$as_me:$LINENO: error: $GSLERROR" >&5
+echo "$as_me: error: $GSLERROR" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "$ac_cv_lib_gslcblas_cblas_dgemm" != yes
+then
+  { { echo "$as_me:$LINENO: error: $GSLERROR" >&5
+echo "$as_me: error: $GSLERROR" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "$ac_cv_lib_gsl_matrix" != yes
+then
+  { { echo "$as_me:$LINENO: error: $GSLERROR" >&5
+echo "$as_me: error: $GSLERROR" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
